version: '3.6'

services:
  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - mongo-blabs:/data/db

volumes:
  mongo-blabs:
